Repository epsagon/cisco-otel-lambda, pull requests merged in 2022-06, with the labels that each got.

#2 Fix/Remove Build Files
  nodejs/src/utils.d.ts
  nodejs/src/utils.d.ts.map
  nodejs/src/utils.js
  nodejs/src/utils.js.map
  nodejs/src/wrapper.d.ts
  nodejs/src/wrapper.d.ts.map
  nodejs/src/wrapper.js
  nodejs/src/wrapper.js.map
Labels: size/M

#3 Feat/Add CICD
  .github/workflows/cd-nodejs.yml
  .github/workflows/ci-nodejs.yml
  nodejs/Makefile
  nodejs/package.json
  nodejs/src/utils.ts
  nodejs/src/wrapper.ts
Labels: size/L

#5 Fix/Disable AWS Propagation
  nodejs/src/wrapper.ts
Labels: size/XS

#6 Feat/Readme
  .github/workflows/cd-nodejs.yml
  README.md
Labels: size/M

#8 Fix/Readme
  README.md
Labels: size/XS

#9 added eu to cd
  .github/workflows/cd-nodejs.yml
Labels: size/XS

#10 update ci cd so every change will trigger the workflow
  .github/workflows/cd-nodejs.yml
  .github/workflows/ci-nodejs.yml
Labels: size/XS

#11 Feat/ARN Readme
  .github/workflows/cd-nodejs.yml
  README.md
Labels: size/S

#12 add service name to options
  README.md
Labels: size/XS

#13 Add service name
  README.md
Labels: size/XS

#14 Add service name
  README.md
Labels: size/XS
